import { Flex } from '@chakra-ui/layout';
import { Button } from '@chakra-ui/react';
import type { NextPage } from 'next';
import { getSession, GetSessionParams, signIn } from 'next-auth/react';
import Head from 'next/head';
import TopBar from '../components/TopBar';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>ToDo App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TopBar />
      <Flex className={styles.main}>
        <Button
          variant="solid"
          bg="#eef2f7"
          color="#172331"
          onClick={() => signIn()}
        >
          Get started
        </Button>
      </Flex>
    </div>
  );
};

export default Home;

export async function getServerSideProps(
  context: GetSessionParams | undefined
) {
  const session = await getSession(context);

  if (session) {
    return {
      redirect: {
        destination: '/logged',
        permanent: false
      }
    };
  }

  return {
    props: {}
  };
}
