import { Flex } from '@chakra-ui/layout';
import { Button } from '@chakra-ui/react';
import type { NextPage } from 'next';
import Head from 'next/head';
import { TopBar } from '../components';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>ToDo App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TopBar />
      <Flex w={['100%', '100%', '100%', '90ch']} className={styles.main}>
        <Button variant="solid" bg="#eef2f7" color="#172331">
          Get started
        </Button>
      </Flex>
    </div>
  );
};

export default Home;
